FROM ubuntu:22.04
ARG GOVERSION=1.22.2
ARG PYTHON_VERSION=3.12
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y \
    git \
    jq \
    libatomic1 \
    nano \
    net-tools \
    netcat \
    curl \
    wget \
    sudo \
    locales \
    && locale-gen en_US.UTF-8 \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
RUN wget https://go.dev/dl/go${GOVERSION}.linux-amd64.tar.gz -O go.tar.gz \
    && tar -C /usr/local -xzf go.tar.gz \
    && rm go.tar.gz
ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
RUN apt update && apt install -y \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt update \
    && apt install -y python${PYTHON_VERSION} python3-pip \
    && apt clean && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 1 \
&& update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN curl -fsSL https://code-server.dev/install.sh | sh
EXPOSE 3080
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /home/pknelo
RUN adduser --disabled-password --gecos '' pknelo && \
    echo "pknelo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER pknelo
ENTRYPOINT ["code-server", "--bind-addr", "0.0.0.0:3080", "--auth", "password"]
CMD ["--disable-telemetry"]
ENV PASSWORD=password 
#must change / debes cambiarla
